<?php

/**
 * @file
 * Module principal SphereVoices.
 *
 * Contient les fonctionnalités spécifiques au site d'information.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function spherevoices_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.spherevoices_core':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module principal pour les fonctionnalités spécifiques à SphereVoices.') . '</p>';
      return $output;

    default:
  }
}

